cilium/statedb

benchmarks_test.go, db.go, db_test.go, deletetracker.go, graveyard.go, metrics.go, table.go, txn.go, types.go
Various optimizations:
- Switch storing of tables and indexes from iradix to simple arrays.
- Drop callerPackage as it was very costly and use a named handle instead (we can easily inject the module name as part of cell.Module using a module provider).
- Rework the benchmarks to use constant data set size to avoid using too much memory.
Before:
```
goos: linux
goarch: amd64
pkg: github.com/cilium/statedb
cpu: Intel(R) Core(TM) i5-10210U CPU @ 1.60GHz
BenchmarkDB_WriteTxn_1-8                                          132523              9268 ns/op            107899 objects/sec
BenchmarkDB_WriteTxn_10-8                                         367114              3044 ns/op            328531 objects/sec
BenchmarkDB_WriteTxn_100-8                                        430207              2459 …
```
=> Various optimizations

reconciler/reconciler.go, reconciler/reconciler_test.go, table.go, types.go
It's often important to avoid pruning data before the table has been fully populated by writers. Add support for this in the form of table initializers that can be registered before the application starts. Make the reconciler pruning conditional on the table being fully initialized.
The initializers are stored in the table entry, which means that the initializer count is coupled to the snapshot and thus a reader won't think the table is initialized before it gets a snapshot that indeed is initialized.
Example:
```
// Adding an initializer (called before start)
txn := db.WriteTxn(myTable)
done := myTable.RegisterInitializer(txn)
txn.Commit()
rtxn1 := db.ReadTxn()
myTable.Initialized(rtxn1) == false
txn = db.WriteTxn(myTable)
done(txn)
txn.Commit()
rtxn2 := db.ReadTxn() …
```
=> Add support for table initializers to gate keep pruning

iterator.go, iterator_test.go
Filter iterator ranges over the objects and skips the ones for which the predicate is not true.  The commit fixes the wording of the function docstring that was stating the opposite.
Add a simple unit test to validate Filter iterator semantic.
=> Fix Filter iterator docstring

db.go, db_test.go, fuzz_test.go, index/keyset.go, index/string.go, table.go, types.go
Add the Prefix() method for doing a prefix search on a table:
```
var tbl Table[Foo]
var index Index[Foo, string]
tbl.Insert(wtxn, Foo{"foo"})
tbl.Insert(wtxn, Foo{"foobar"})
wtxn.Commit()
iter, watch := tbl.Prefix(db.ReadTxn(), index.Query("fo"))
// returns "foo" and "foobar", the watch channel will be the channel
// of the parent of "foo" since that's the most specific one.
```
=> Add support for prefix searching

txn.go
It's unused since commit 965dc5bb488b ("Use arrays for index tree lookup").
=> Remove unused type tableIndex

README.md, benchmarks_test.go, db_test.go, deletetracker.go, doc.go, fuzz_test.go, go.mod, go.sum, graveyard.go, iterator_test.go, part/iterator.go, part/node.go, part/ops.go, part/part_test.go, part/tree.go, part/txn.go, reconciler/benchmark/main.go, table.go, txn.go, types.go
Switch StateDB to use custom implementation of Persistent Adaptive Radix Trees (https://db.in.tum.de/~leis/papers/ART.pdf).
The implementation isn't a completely fateful implementation of the paper. The Node16 SIMD tricks and Node48 key array are skipped. This made the implementation simpler, but did leave some performance improvements on the table.
The only functional change to StateDB is to drop the `Last` and `LastWatch` methods since that requires an reverse iterator implementation and since we didn't use them we can just drop them for now.
Benchmark before:
```
goos: linux                                                                                                                                                                                     
goarch: amd64 …
```
=> Switch to persistent adaptive radix trees

db.go, go.mod, http.go, http_client.go, http_test.go, txn.go, types.go
Simple HTTP JSON API for dumping and querying the database.
Example usage:
```
var db *statedb.DB
http.Handle("/db", statedb.NewHTTPHandler(db))
go http.ListenAndServe(":8080")
url, _ := url.Parse("http://localhost:8080/db")
var table *statedb.Table[*Example]
var index *statedb.Index[*Example, string]
remoteTable := statedb.NewRemoteTable(url, table.Name())
iter, errs := remoteTable.Get(ctx, index.Query("foo"))
for obj, rev, ok := iter.Next(); ok; obj, rev, ok = iter.Next() {
...
}
if err := <-errs; err != nil {
// handle error
}
iter, errs = remoteTable.LowerBound(ctx, statedb.ByRevision(0))
...
```
=> Add HTTP API and RemoteTable[Obj]

.github/workflows/main.yml, .github/workflows/pr.yml, Makefile, benchmarks_test.go, db_test.go, deletetracker.go, derive.go, fuzz_test.go, graveyard.go, iterator.go, observable.go, part/iterator.go, part/node.go, part/part_test.go, reconciler/benchmark/main.go, table.go, txn.go, types.go
DeleteTracker() is confusing to users. It is essentially just providing an iterator for updates and deletes, so let's call it that: Changes().
```
var tbl Table[*Foo]
iter, err := tbl.Changes(db.ReadTxn())
if err != nil { return }
defer iter.Close()
for {
for ev, rev, ok := iter.Next(); ok; ev, rev, ok = iter.Next() {
if ev.Deleted {
// ev.Object deleted
} else {
// ev.Object created or updated
}
}
select {
case <-ctx.Done():
return
case <-iter.Watch():
}
}
```
Functional difference to before is that this does not allow "reiterating" as one could do with DeleteTracker's IterateWithError that stops on error and allows picking up iteration again to retry. But that's not needed with Changes() as the caller can take care of retrying the failed event before iterating again.
=> Introduce Changes() API

http.go, http_client.go, http_test.go
Finish the http /dump test.
Add SetTransport to `RemoteTable[Obj]` to allow cilium-dbg to override the transport for doing requests over UNIX socket.
Switch "POST /query" to "GET /query"
=> Fix http test and add SetTransport

benchmarks_test.go, part/cache.go, part/node.go, part/part_test.go, part/tree.go, part/txn.go
Implement few more of the optimizations in the paper. Namely do linear search for node4 & node16, embed the key array into the nodes and use a 256-ary index array in node48 for direct lookup instead of binary search.
Use a small cache for node reuse instead of a hash map. The cache hashes some bits of the pointer for direct lookup into an array. In benchmarks this yields better performance without a significant change to average number of allocations.
Benchmark results:
```
Part (-count 10):
│   old.txt    │               new.txt                │
│ objects/sec  │ objects/sec  vs base                 │
_Insert_RootOnlyWatch-8    3.026M ±  6%   4.193M ± 5%   +38.56% (p=0.000 n=10)
_Insert-8                  2.511M ±  4%   3.084M ± 4%   +22.83% (p=0.000 n=10)
_Replace-8 …
```
=> part: Optimizations to node layout

reconciler/reconciler.go, reconciler/reconciler_test.go, reconciler/types.go
Noticed that we need the ability to provide the default metrics implementation in cilium/cilium as most reconcilers would not want their own specific implementation. It would be unnecessary boilerplate to have to depend on metrics and pass it in the configuration, so add it as an optional to Params[T].
=> reconciler: Add ability to provide default metrics

reconciler/benchmark/main.go, reconciler/example/main.go, reconciler/example/types.go, reconciler/full.go, reconciler/incremental.go, reconciler/reconciler_test.go, reconciler/types.go
We need to sometimes augment the object based on the result of the operation. Modify the reconciler to allow for this by adding a CloneObject function to the configuration and clone the object before passing it to the operations.
The concrete use-case for this is in Cilium's load-balancing control-plane where the low-level operations would allocate a numeric identity to a service during the reconciliation and we want to expose this for debugging purposes in the object.
=> reconciler: Add the ability to mutate object from operations

reconciler/benchmark/main.go, reconciler/example/main.go, reconciler/full.go, reconciler/incremental.go, reconciler/reconciler.go, reconciler/reconciler_test.go, reconciler/types.go
With Hive cannot currently have to private providers for the same type, even when they're in different scopes. To allow for the situation where the RWTable is provided privately in one module, but still accessible via a method for reconciliation use, move the Table from Params to Config so it can be provided directly and not via Hive.
The exact setup where this problem occurred was:
```
// module 1
var Cell = cell.Module(...,
cell.ProvidePrivate(NewRWTableFoo),
cell.Provide(NewWriter),
),
type Writer struct {
table RWTable[Foo]
}
func NewWriter(t RWTable[Foo]) *Writer
func (w *Writer) UnsafeRWTable() RWTable[Foo] { return w.table }
// module 2
var Cell = cell.Module(...,
cell.ProvidePrivate((*m1.Writer).UnsafeRWTable),
cell.Invoke(reconciler.Register[Foo]),
)
```
The above lead to:
``` …
```
=> reconciler: Move Table from Params to Config

fuzz_test.go, part/node.go, part/part_test.go, part/txn.go
If we insert "foobar" and then "foo" we ended up in a case where "foo" was the common prefix and the rest of the key become empty leading to out-of-bounds access to the key slice.
Handle the case where the key becomes empty when splitting a node by just inserting it as the leaf of the split node.
Added a regression test and validated it catched the bug:
```
--- FAIL: Test_prefix_regression (0.00s)
panic: runtime error: index out of range [0] with length 0 [recovered]
panic: runtime error: index out of range [0] with length 0
goroutine 32 [running]:
testing.tRunner.func1.2({0x5f3380, 0xc00001a288})
/home/jussi/sdk/go1.22.0/src/testing/testing.go:1631 +0x24a
testing.tRunner.func1()
/home/jussi/sdk/go1.22.0/src/testing/testing.go:1634 +0x377
panic({0x5f3380?, 0xc00001a288?}) …
```
=> part: Fix bug with short and long key with shared prefix

iterator.go, reconciler/benchmark/main.go, reconciler/example/main.go, reconciler/full.go, reconciler/helpers.go, reconciler/incremental.go, reconciler/reconciler.go, reconciler/reconciler_test.go, reconciler/types.go, table.go, txn.go, types.go
To be able to use multiple reconcilers against a single object we cannot do soft-deletes and have the reconciler delete the object, as then we would have multiple reconcilers wanting to delete the same object.
To fix this, drop the StatusKindDelete and use the ChangeIterator to iterate over both inserts and deletes.
The downside is that we can't observe failed deletions via the table, but it will be visible via module health. On the other hand, it is less confusing to users to not have deleted objects visible in the tables.
=> reconciler: Remove StatusKindDelete

README.md, benchmarks_test.go, db_test.go, derive.go, fuzz_test.go, reconciler/benchmark/main.go, reconciler/example/main.go, reconciler/incremental.go, reconciler/reconciler.go, reconciler/reconciler_test.go, regression_test.go, table.go, types.go
The First() method name has been an eye sore from the start. This is now a good point to rename it as we're about to switch Cilium to using cilium/statedb and need to refactor a bunch of code anyway.
Before:
```
obj, rev, found := table.First(txn, MyIndex.Query("foo"))
obj, rev, found, watch := table.FirstWatch(txn, MyIndex.Query("foo"))
iter, watch := table.Get(txn, MyIndex.Query("foo"))
```
Now:
```
obj, rev, found := table.Get(txn, MyIndex.Query("foo"))
obj, rev, found, watch := table.GetWatch(txn, MyIndex.Query("foo"))
iter := table.List(txn, MyIndex.Query("foo"))
iter, watch := table.ListWatch(txn, MyIndex.Query("foo"))
```
=> Rename First to Get and Get to List/ListWatch

reconciler/reconciler_test.go, reconciler/types.go
Before: "done (updated: 4.734193304s ago)"
After: "Done (4.7s ago)"
=> reconciler: Make the Status.String() prettier

reconciler/benchmark/main.go, reconciler/example/ops.go, reconciler/full.go, reconciler/incremental.go, reconciler/metrics.go, reconciler/reconciler_test.go, reconciler/types.go
The "changed *bool" passed to Update() was confusing and it was often not easy or cheap to check whether the target had the expected value or not.
Let's err on the side of simplicity and drop the "out-of-sync" metric for the time being.
=> reconciler: Drop out-of-sync metric and changed parameter from Update

benchmarks_test.go, db_test.go, derive_test.go, http_test.go, part/map.go, part/map_test.go, part/registry.go, part/set.go, part/set_test.go
While trying to use part.Map and part.Set in some real-world code I quickly realized it was missing support for JSON marshalling and unmarshalling. To implement this we need a way to implement `func (m *Map[K, V) UnmarshalJSON(data []byte) error` and for that to work the zero value has to be usable. To get around this and in general make these a bit easier to use this PR moves the "toBytes" into a global registry rather than passing these functions in with `NewMap` and so on. **Is this easy enough to use?**, e.g. to use part.Map with a new key type one does this:
```
type MyKey string
func init() {
part.RegisterKeyType(func(k MyKey) []byte { return []byte(k) })
}
```
If this is not done, then e.g. `Map.Set` will panic telling the user to do this. In some sense this idea is similar to e.g. …
=> part: Map/Set zero values and JSON marshalling

db_test.go, derive_test.go, reconciler/example/main.go, reconciler/example/types.go, reconciler/reconciler.go, reconciler/reconciler_test.go, regression_test.go, table.go, types.go
```
Support named table initializers
Add support for naming the table initializer and the ability to check if a
specific table initializer is still pending. This will be needed in Cilium
for implementing the two-stage GC'ing of local and remote (ClusterMesh)
services, so I'm adding this in already.
Example:
var t RWTable[Foo]
wtxn := db.WriteTxn(t)
done := t.RegisterInitializer(txn, "example")
wtxn.Commit()
txn := db.ReadTxn()
t.Initialized(txn) == false
t.PendingInitializers(txn) == []string{"example"}
wtxn = db.WriteTxn(t)
// Initialize the table
t.Insert(wtxn, Foo{...})
...
done(wtxn)
wtxn.Commmit()
// The old ReadTxn/snapshot of course still uninitialized.
t.Initialized(txn) == false
txn = db.ReadTxn()
t.Initialized(txn) == true
t.PendingInitializers(txn) == []string{}
Signed-off-by: …
```
=> Add support for named initializers

reconciler/full.go, reconciler/incremental.go, reconciler/metrics.go, reconciler/reconciler.go, reconciler/reconciler_test.go, reconciler/retries.go, reconciler/retries_test.go, reconciler/types.go
```
reconciler: Do not query for object when retrying
There's no need to requery for the object when retrying as the entry will be
cleared from the queue if it has changed.
This will also retain the original status of the object which allows the
operations to distinquish whether the Update() call is a retry of a normal
update or a refresh.
Signed-off-by: Jussi Maki <jussi.maki@isovalent.com>
reconciler: Fix health reporting of retries
The objects waiting for retry were not properly reflected in the health
status. A reconciliation round after the failures cleared the health status
rather than reflected the number of objects still waiting for retry.
Fix this by remembering the error in the retry queue items and returning 
those. Also modify the metrics implementation to properly reflect the …
```
=> Fixes for v0.1.0 release

part/part_test.go, part/quick_test.go, part/txn.go
Add generative QuickTests to test out different
operations on generated inputs.
Fix the bug with closing the watch channel when
deleting single element tree with a zero-sized key.
=> part: Add QuickTests

README.md, benchmarks_test.go, db_test.go, derive_test.go, fuzz_test.go, iterator.go, iterator_test.go, reconciler/benchmark/main.go, reconciler/reconciler.go, table.go, types.go
Add *Watch variants to LowerBound, Prefix and All to make them work the same way as List and Get.
=> Fix API asymmetries with Watch variants

reconciler/incremental.go, reconciler/multi_test.go, reconciler/reconciler_test.go, reconciler/status_test.go, reconciler/types.go
In order to efficiently support multiple reconcilers per object we need to make the reconciler aware of whether the object's data changed versus whether the reconciliation status changed. The current implementation only checked whether the object has a new revision when committing the reconciliation status, but in the presence of multiple reconcilers per object we need to actually check if the object was asked to be re-reconciled.
This commit adds the notion of "pending id" to 'Status' which allows the reconciler to compare the id of the object it reconciled with the id of the current object in the database and update it if the ids still match, regardless of the revision.
To make it easier to implement reconcilers for an object where the set of reconcilers is unknown beforehand, implement …
=> reconciler: Add StatusSet and optimize for multiple reconcilers

reconciler/reconciler.go, reconciler/reconciler_test.go
The refresh loop was supposed to wait until the oldest object's UpdatedAt time exceeds the RefreshInterval. Unfortunately the calculation was reversed (`UpdatedSince - RefreshInterval` when it should've been `RefreshInterval - UpdatedSince`) and the refresh duration to wait became negative, which caused the refreshLoop to busy-loop looking for the next object to refresh. 
This did not affect correctness as the timer was only used to wait before checking for expired objects and thus was not catched.
Before: 
```
agent.datapath.sysctl                            job-refresh     OK      Refreshing in -2m39.041586521s ...    
```
(job-refresh busy-loop'd constantly updating the health and resetting the timer to a negative value which then immediately fired)
After:
```
agent.datapath.sysctl …
```
=> reconciler: Fix refresh timer calculation

part/map.go, part/map_test.go, part/set.go, part/set_test.go
The Delete() method used Tree.Delete which did a Commit that closed all watch channels. For part.Map and part.Set we do not want the watch channel functionality and instead should use CommitOnly().
=> part: Fix part.Map's Delete

db.go, errors.go, table.go, txn.go
If a user forgets to register a table with the DB instance and then proceeds to use it, the tablePos defaults to 0. This causes writes to the table to end up in the wrong table.
This commit defaults the table pos to -1 to cause deliberate panics if the code ever attempts to use the index of a unregistered table. This commit also adds checks on the read and write transactions to detect when an unregistered table is being used and throw a clear error.
=> statedb: Add checks to see if table is registered

db_test.go, table.go, txn.go, types.go
Both NumObjects() and Initialized() returned the committed state and not the currently modified state:
```
txn := db.WriteTxn(tbl)
tbl.NumObjects(txn) == 0
tbl.Insert(txn, Foo{})
tbl.NumObjects(txn) == 0 !!!
init := tbl.RegisterInitializer("test")
tbl.Initialized(txn) == false
init(txn)
tbl.Initialized(txn) == false !!!
```
=> Fix NumObjects and Initialized with WriteTxn

benchmarks_test.go, db_test.go, part/part_test.go, part/tree.go, part/txn.go, table.go, txn.go, types.go
This adds Modify() to `part` and to `RWTable[T]`. 
Modify() can be used in Cilium to efficiently implement merging of external data into internal objects
that carry state that we want to merge with rather than replace. A follow-up PR in cilium/cilium will
add the merging support to `pkg/k8s/statedb.go`.
=> Add Modify() method

db_test.go, table.go
The initial watch channel used by ChangeIterator is the one returned by the LowerBound search. This only closes when there are new changes and thus would block even if there would be changes to iterate.
To make this easier to use correctly, use a closed watch channel to start with so it doesn't matter whether the changes are iterated first and then Watch() is called or the other way around.
=> Start with closed watch channel in Changes()

.github/workflows/pr.yml, benchmarks_test.go, part/part_test.go
If a PR fails the failed "make test" output wasn't posted. Add a "if: always()" to the comment posting to always post it.
This was manually tested.
Fix the secondary index benchmark not to recreate the tags set on each insert as that's not what is important for the benchmark.
Additionally drop the very large batch sizes from benchmarks as those use up fair bit of memory and don't provide a useful signal.
=> Fix comment posting on failed CI run and cleanup benchmarks

db_test.go, reconciler/reconciler.go, reconciler/reconciler_test.go, table.go, types.go
Pruning should be performed when the table has initialized even when the table is empty. To implement this a watch channel is added for initialization and Initialized() now returns (bool, <-chan struct{}).
The reconciler can now wait for initialization and immediately trigger the pruning.
=> reconciler: Prune after initialized even with empty table

db.go, http.go, http_client.go, http_test.go, iterator.go, table.go, types.go
This allows streaming changes (upserts and deletes) over the HTTP API.
Example usage:
```
examples := statedb.NewRemoteTable[*Example](url, "examples")
// Stream changes until [ctx] is cancelled.
changes, errChan := examples.Changes(ctx)
for change, rev, ok := changes.Next(); ok; change, rev, ok = changes.Next() {
example := change.Object
if change.Deleted {
// deleted
} else {
// upserted
}
}
err := <-errChan
```
=> http: /changes API for streaming changes

fuzz_test.go, go.mod, graveyard.go, reconciler/helpers.go
The former is available since Go 1.21 and the latter is merely a wrapper around it when using Go ≥ 1.21. Use the standard library package directly.
We cannot yet switch out `x/exp/maps` for the standard library `maps` package as the `maps.Keys` function used in `statedb` code base is only available in Go ≥ 1.23.
=> Use Go standard library slices package instead of x/exp/slices

db.go, reconciler/example/main.go, reconciler/metrics.go
This removes the separate `Handle` type to allow decorating `DB` with the handle name in Hive:
```
hive.Options{
// Create a named DB handle for each module.
ModuleDecorator: func(db *statedb.DB, id cell.ModuleID) *statedb.DB {
return db.NewHandle(string(id))
},
},
```
With this we can get StateDB metrics accounted by module, allowing us to for example seeing which module
has long-running `WriteTxn`s etc.
=> Unify DB and Handle types into just DB

table.go, txn.go
The function to mark a table initialized wrongly closed the channel immediately. This could cause an observer to be woken up too early (before Commit() has finished) and get an uninitialized snapshot.
Fix the timing issue by moving the closing into Commit(), next to the normal watch channel closing. This way the initialized table has been committed before the init watch channel closes.
This issue was detected by `pkg/k8s/statedb_test.go` in cilium/cilium:
```
statedb_test.go:263:
Error Trace:	/home/runner/work/cilium/cilium/pkg/k8s/statedb_test.go:263
/home/runner/work/cilium/cilium/pkg/k8s/statedb_test.go:120
Error:      	Not equal:
expected: "obj1"
actual  : "garbage"
Diff:
--- Expected
+++ Actual
@@ -1 +1 @@
-obj1
+garbage
Test:       	TestStateDBReflector/default
```
=> Fix race with table init channel

any_table.go, benchmarks_test.go, db_test.go, http.go, iterator.go, quick_test.go, regression_test.go, table.go, txn.go
Prefix and LowerBound searches did not properly deal with non-unique indexes. In these indexes the keys are encoded as <secondary><primary><secondary len>, and prefix searching needs to make sure the secondary key length on the results is equal or longer than the search key as otherwise we might match into the primary key.
For example if the object is struct{A, B string}, with A being primary and we have {"a", "a"}, then the secondary index is key'd as "aa<1>". A prefix search with "aa" must not match since the secondary index contains only an object with key "a".
Fix this by using a special iteration on non-unique indexes that checks the length of the secondary key and ignores any other matches that are due to matching into the primary key.
=> Fix Prefix and LowerBound on non-unique indexes

any_table.go, go.mod, go.sum, script.go
The 'watch' command allows watching a table for changes, similar to the `cilium-dbg statedb <table> --watch` flag. The "strike out" support is ported from cilium-dbg/cmd/statedb.go.
The plan is to eventually replace the "cilium-dbg statedb" with the script commands.
```
❯ go run .
> hive start
...
time=2024-10-11T12:25:45.489+02:00 level=INFO msg=Started duration=177.609µs
> db watch ex
Name    X
one     1
two     2
count   0
count   1
count   2
...
^C (interrupted)
> 
```
=> script: Add watch command

script.go, script_test.go
The takeColumns function assumed that the column indexes were ordered, e.g. if the table header was "Foo Bar Baz", then it'd always be referenced in order: "Foo" or "Foo Baz" but never "Baz Foo". There's no reason to assume that, so fix this and add tests.
=> script: Fix comparison of non-ordered columns

go.mod, go.sum, reconciler/script_test.go, script.go, script_test.go, testdata/db.txtar
The "db show -format=json" was missing newline at the end. While at it, switch to MarshalIndent for nicer output and extend the tests.
Hive dependency is bumped to add the -scripttest.update support.
=> Fix JSON formatting in db show command

reconciler/status_test.go, reconciler/types.go
43587d4f2fbe broke JSON marshalling of Status by introducing a separate statusJSON type and Unmarshal{JSON,YAML} methods, but didn't introduce the Marshal{JSON,YAML} methods, which caused dictionary key mismatches as Status struct was used to marshal instead of statusJSON.
Fix this by removing the whole statusJSON construct and add json and yaml tags to Status. There is no need for filling in the `id` field when unmarshalling Status as this is completely internal to the reconciler.
Fixes: 43587d4f2fbe ("reconciler: Implement tests using scripttest")
=> reconciler: Fix Status JSON marshalling

part/map.go, part/map_test.go, part/set_test.go
MarshalYAML nil deref'd the 'm.tree' when the map was empty. Fix this and extend test coverage.
=> part: Fix MarshalYAML on empty maps

reconciler/incremental.go, reconciler/script_test.go, reconciler/status_test.go, reconciler/testdata/batching.txtar, reconciler/testdata/incremental.txtar, reconciler/testdata/pruning.txtar, reconciler/testdata/refresh.txtar, reconciler/types.go
The fix to JSON status marshalling had the unintended effect that now the reconciler test suite ran with the ID field being uninitialized, leading to the reconciler overwriting the status of a changed object. This resulted in small fraction of the reconciler test runs failing (e.g. object was marked pending, but instead of being re-reconciled the previous status was inserted).
This did not affect non-test code as status should always be constructed with StatusPending() etc.
Fix this by exporting the ID and filling it in the tests.
Fixes: 132edd67f709 ("reconciler: Fix Status JSON marshalling")
=> reconciler: Fix flake in reconciler tests due to ID being unset

reconciler/testdata/batching.txtar, reconciler/testdata/incremental.txtar, reconciler/testdata/pruning.txtar, reconciler/testdata/refresh.txtar, script.go, testdata/db.txtar
The user experience with commands that have sub-commands is not great and it makes it harder to implement completion in 'cilium-dbg shell' if we so choose. There isn't really any good rational for nesting the commands like this, so let's go with Plan 9 style command names (https://9p.io/magic/man2html/8/auth), e.g. "db prefix" becomes "db/prefix".
=> Flatten the 'db' commands, e.g. 'db prefix' to 'db/prefix'

watchset.go, watchset_test.go
When writing a controller that needs to react to specific queries changing it's useful to be able to watch a dynamic set of channels. Add the [WatchSet] utility for this.
Example use:
```
var names []string = ...
ws := statedb.NewWatchSet()
for {
for _, name := range names {
things, watch := myTable.ListWatch(txn, ThingsByName(name))
ws.Add(watch)
processThings(things)
}
// Wait for things that have a name in 'names' to change.
if err := ws.Wait(ctx); err != nil {
// Context cancelled
break
}
}
```
=> Add WatchSet for watching a dynamic set of channels

any_table.go, db_test.go, part/part_test.go, part/txn.go, table.go, txn.go, types.go
The InsertWatch returns the new watch channel for the inserted objects allowing waiting for subsequent changes without having to do a separate query to retrieve the watch channel.
Example:
```
txn := db.WriteTxn(table)
old, hadOld, watch, err := table.InsertWatch(txn, myObject{ID: 1})
txn.Commit()
txn = db.WriteTxn(table)
table.Insert(txn, myObject{ID: 1})
txn.Commit()
<-watch // this is now closed
```
=> Add InsertWatch operation

watchset.go, watchset_test.go
It is not very uncommon that we'd add duplicate channels to the watch set, so better deduplicate.
Add Merge() and Has() methods. These are useful when we need to know whether a closed channel affected a particular subset of work.
=> watchset: Use a map for channels and add Merge and Has

any_table.go, db_test.go, http.go, iterator.go, quick_test.go, table.go, txn.go, types.go
The query results for non-unique indexes were sorted properly by the secondary key, but not by primary due to the substition scheme not properly retaining the order. Fix this by using the following scheme:
```
0x00 => 0x0101
0x01 => 0x0102
```
This ensures that the original ordering is retained. Additionally also encode the secondary key using this scheme to make sure 0x00 in the secondary key does not mess the results.
The TestDB_Quick was extended to validate that the query results for non-unique indexes are properly sorted by both the primary and secondary keys.
=> Fix ordering of query results on non-unique indexes

watchset.go, watchset_test.go
Instead of a set of goroutines doing select use reflect.Select instead as it's a bit faster and allocates less.
Benchmark before:
```
goos: linux
goarch: arm64
pkg: github.com/cilium/statedb
BenchmarkWatchSet_4
BenchmarkWatchSet_4-6             633849              2027 ns/op             736 B/op         15 allocs/op
BenchmarkWatchSet_16
BenchmarkWatchSet_16-6            273488              4521 ns/op            1232 B/op         18 allocs/op
BenchmarkWatchSet_128
BenchmarkWatchSet_128-6            48825             24887 ns/op            5653 B/op         28 allocs/op
BenchmarkWatchSet_1024
BenchmarkWatchSet_1024-6            5077            262523 ns/op           55920 B/op        109 allocs/op
```
Benchmark after:
```
goos: linux
goarch: arm64
pkg: github.com/cilium/statedb …
```
=> Use reflect.Select for WatchSet

reconciler/benchmark/main.go, reconciler/example/ops.go, reconciler/incremental.go, reconciler/multi_test.go, reconciler/script_test.go, reconciler/types.go
For symmetry with BatchOperations add the object revision to the [Operations.Update] and [Operations.Delete].
Fixes: #56
=> reconciler: Add revision to Update and Delete ops

.github/workflows/pr.yml
The posting of the test run as a comment used `make | tee out` which without `pipefail` ate the exit status from `make`. Use `set -o pipefail` in the jobs to properly propagate this. While at it, simplify the workflow a bit.
In case you're wondering why post a comment at all: this is my simple way of easily keeping track of the code test coverage and the benchmark numbers (I always check the reconciler throughput for example). This will also leave a trace of which PR potentially started causing regressions (unreliable of course due to benchmarks running potentially different hardware, but it's something).
=> CI: Fail action if make fails (pipefail oops)

benchmarks_test.go, fuzz_test.go, part/map_test.go, part/part_test.go, script.go, watchset_test.go
Diff generated by:
go run golang.org/x/tools/gopls/internal/analysis/modernize/cmd/modernize@latest -fix -test ./...
Mostly due to the bump to 1.24 :)
=> treewide: modernize for 1.24

part/part_test.go, part/tree.go
To allow forking the tree into two lineages we'll need to make sure only the first Txn() call will reuse the allocation and pass it to the produced tree.
Also drop the pre-allocation of 'Txn' in 'New'. It'll be produced by the first 'Txn()' call and we'll use less memory for empty trees this way.
=> part: Clear tree.txn after reusing it

part/map.go, part/map_test.go, part/quick_test.go
In cilium/cilium we're using part.Map in the Backend object to hold the instances of the backend and most of the time it only contains one element.
Specialize for this case by adding a singleton field to part.Map.
Before (map with 1 element):
```
=== RUN   TestMapMemoryUse
map_test.go:272: 320 bytes per map
```
After:
```
=== RUN   TestMapMemoryUse
map_test.go:348: 40 bytes per map
```
pkg/loadbalancer/benchmark before:
```
Memory statistics from N=10 iterations:
Min: Allocated 716852kB in total, 2068061 objects / 125960kB still reachable (per service:  41 objs, 14681B alloc,  2579B in-use) 
Avg: Allocated 731848kB in total, 2607405 objects / 180868kB still reachable (per service:  52 objs, 14988B alloc,  3704B in-use) 
Max: Allocated 775441kB in total, 3649005 objects / 317829kB still …
```
=> part: Optimize map space usage with one element

index/string.go
Since index.Key is never mutated and the Go string is immutable we can safely just cast the string into index.Key and avoid a copy.
=> index: String() can just cast to index.Key

db_test.go, write_txn.go
Currently, the information about the last WriteTxn is not reported correctly, as the internal variables are reset once a transaction gets committed or aborted. Let's get this fixed by only resetting the other fields, and add a new unit test to prevent regressions.
=> statedb/txn: correctly report information about the last WriteTxn

db_test.go, table.go
Currently, [Table.Initialized] is affected by a potential pitfall, as it can return false (i.e., not initialized) and a closed watch channel if any write transaction (e.g., to populate an initial state, or register a changes iterator) completed before the first initializer is registered. Similarly, the same can happen if a new initializer is registered after that the previous ones have already been marked as done. In turn, this can cause consumers to misbehave, e.g., entering a busy loop, or incorrectly thinking that the table is initialized, if relying on the channel only.
Let's get this fixed by slightly reworking the internal handling of initialized, so that we correctly support multiple transitions for the same table between initialized and not initialized. The initializations status …
=> statedb/table: allow multiple initialized transitions

script.go
The db/* command detailed help text wasn't updated after the change to pflag based script flag parsing, e.g. '-columns' should have been '--columns' etc.
Fixes: cc7f9619b1bc ("Refactor to use the new flags system in script")
=> Fix script command detailed help

any_table.go, benchmarks_test.go, derive_test.go, fuzz_test.go, iterator_test.go, quick_test.go, reconciler/benchmark/main.go, reconciler/example/types.go, reconciler/multi_test.go, regression_test.go, script.go, table.go, types.go
Let's start enforcing the TableWritable on the tables so we have proper "db/show" output for all tables.
To make it possible to have StateDB tables without having to introduce a wrapper type for types we don't control add a NewTableAny constructor which takes TableHeader() and TableRow() as arguments.
=> statedb: Add TableWritable as constraint on NewTable, add NewTableAny

go.mod, go.sum, script.go
This commit updates the hive dependency and adds autocomplete functionality for the script commands.
A practical example of the proposed hive script tab completion.
This PR is blocked on https://github.com/cilium/hive/pull/57, we should bump hive dependency to a proper release as soon as the PR merges.
=> script: Add script autocomplete functionality

README.md
Update the README to include TableHeader() & TableRow() examples as a previous commit added the TableWritable constraint to NewTable().
=> Add TableWritable methods to MyObject in README.md

reconciler/script_test.go, reconciler/status_test.go, reconciler/testdata/refresh.txtar, reconciler/types.go
1. Change `Error` from `string` to `*string` as it's rarely set (64 => 56 bytes)
2. Change `StatusKind` from `string` to `uint8` (56 => 48 bytes)
The `StatusKind` is `struct { uint8 }` to make sure code that used to do `string(foo.Status.Kind)` won't compile and is forced to change to `foo.Status.Kind.String()`. Note that we're going to release v0.5.0 with few other breaking API changes in addition to this one and tooling in cilium/cilium only bumps StateDB on patch version changes.
=> reconciler: Shrink Status type

reconciler/benchmark/main.go, reconciler/builder.go, reconciler/example/main.go, reconciler/script_test.go, reconciler/types.go
To allow using reconciler.Register after the application has started change it to take a job.Group to which to append its jobs instead of having it create one.
=> reconciler: Take a job.Group instead of creating one

db_test.go, types.go
In some cases one may want to construct the raw query key by hand instead of going via the [FromKey] method defined by the index. To allow this add Index[].QueryFromKey() that constructs a Query with the given index.Key.
Example use case: https://github.com/cilium/cilium/pull/41965/files#r2394153881
=> Add Index[].QueryFromKey for querying with raw keys

script.go
This commit changes the script output of the `db` command so that the tables are listed in alphabetical order.
=> script: sort tables in script command "db"
